name: interview
description: "A clean-architecture Flutter app built with **GetX** that fetches and displays top headlines from the News API."
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  either_dart: ^1.0.0
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  curl_logger_dio_interceptor: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/raster/
    - assets/vector/

  fonts:
    - family: dana_regular
      fonts:
        - asset: assets/fonts/dana_regular.ttf